from __future__ import annotations


SYMBOLS = [
    "BTCUSDT",
    "ETHUSDT",
    "SOLUSDT",
    "XRPUSDT",
    "ADAUSDT",
]

INTERVAL = "1m"

CANDLES_PER_SYMBOL = 100

REQUESTED_DURATION_MINUTES = 60

REQUESTED_RANGE_MODE = "ROLLING_END_AT_NOW"

PROVIDER_PRIORITY = [
    "BINANCE_SPOT_PUBLIC",
    "COINBASE_EXCHANGE_PUBLIC",
]

TRADING_ENABLED = False
ORDERS_ENABLED = False
STRATEGY_ENABLED = False

INTERVAL_MS = 60_000

COINBASE_BATCH_LIMIT = 300


assert not TRADING_ENABLED
assert not ORDERS_ENABLED
assert not STRATEGY_ENABLED
