name: Test Actions

on:
  workflow_dispatch:
  push:
    branches: [v4]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Print Python version
        run: python --version

      - name: Print success message
        run: echo "Actions is working"
